[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dol_program = "55wZTBRpDdCt5tEz9dpsKgwmrATUZc6v2237cXQkTgX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/A1.json"

[scripts]
test = "pnpx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
