[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.Devnet]
dol_program = "DoLotrsAZR2JYa4tjue2c5q4EYKMbm6kxcrvjbU5cxX5"

[programs.localnet]
dol_program = "DoLotrsAZR2JYa4tjue2c5q4EYKMbm6kxcrvjbU5cxX5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/A1.json"

[scripts]
test = "pnpx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-dol = "pnpx ts-node scripts/initialize-dol.ts"
check-dol = "pnpx ts-node scripts/init-dol-test.ts"
